development:
  adapter: postgresql
  encoding: unicode
  database: troll_poll_dev
  pool: 5

test: 
  adapter: postgresql
  encoding: unicode
  database: troll_poll_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: troll_poll_pro
  pool: 5
  host: localhost
