development:
  adapter: postgres
  encoding: unicode
  database: troll_poll_dev
  pool: 5
  username: ahmad
  password: password
  host: localhost

test: 
  adapter: postgres
  encoding: unicode
  database: troll_poll_test
  pool: 5
  username: ahmad
  password: password
  host: localhost

production:
  adapter: postgres
  encoding: unicode
  database: troll_poll_pro
  pool: 5
  username: ahmad
  password: password
  host: localhost
  